services:
  - type: web
    name: quiz-battle
    env: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
